### ISSUE TITLE
ModuleNotFoundError: No module named “legged_gym”

### ISSUE THREAD

**Issue by lupinjia** [unitreerobotics/unitree_rl_gym#3]
# Background
I followed the [doc](https://support.unitree.com/home/zh/developer/rl_example) to configure the example, but encountered `ModuleNotFoundError: No module named “legged_gym”` as I tried to run `python3 train.py --task=go2`. 
# Analysis
I doublechecked the `sys.path.append()` line and ensured that I put my local path of `unitree_rl_gym/legged_gym`, but it still threw this error. I'm not sure if this is only my case. 

I referred to [legged_gym](https://github.com/leggedrobotics/legged_gym), rearranged the file structure and added a setup.py. After `pip install -e`, the code could run normally.

The file structure is as follows:
```legged_gym
|—— legged_gym
    |—— envs
    |—— scripts
    |—— utils
|—— resources
|—— setup.py
```

By the way, I think the version of rsl_rl(1.0.2) should be noted in the [doc](https://support.unitree.com/home/zh/developer/rl_example), cauz the newer version is not compatible with this repo

**Comment by xdd7561** [comment]
Hi, were you able to solve this problem? I have same error.

**Comment by lupinjia** [comment]
I have showed the solution in the issue

**Comment by HuangDou228** [comment]
well, there is a simple way to solve this problem.
First, I run `python train.py --task=go2` instead of `python3 train.py --task=go2` in unitree_rl_gym/legged_gym. After that, it reported an error saying that the go2 task is not registered.
Then, I just simply copy `unitree_rl_gym/legged_gym/envs/go2` to `legged_gym/legged_gym/envs/ `and `unitree_rl_gym/resources/robots/go2` to `legged_gym/resources/robots/` and succeed.

**Comment by lupinjia** [comment]
[Official doc](https://support.unitree.com/home/zh/developer/rl_example) has been updated, and this problem is not so tricky, issue close.
